// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDethRgfLvoLbyBgGzVnueOgzColBK_7UI',
    appId: '1:500904711523:web:240af9957f17b07098ef56',
    messagingSenderId: '500904711523',
    projectId: 'pet-well-3d5bb',
    authDomain: 'pet-well-3d5bb.firebaseapp.com',
    storageBucket: 'pet-well-3d5bb.firebasestorage.app',
    measurementId: 'G-YG5PSHP95X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAm_6J5EvFLzyQ3yiMnBiemXvFWq3n1DQ',
    appId: '1:500904711523:android:d897c86d6fa300c698ef56',
    messagingSenderId: '500904711523',
    projectId: 'pet-well-3d5bb',
    storageBucket: 'pet-well-3d5bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUKXEGJ-uSBCP6tw7dKmoYT0VCvS63ziU',
    appId: '1:500904711523:ios:d3303e88388ea90c98ef56',
    messagingSenderId: '500904711523',
    projectId: 'pet-well-3d5bb',
    storageBucket: 'pet-well-3d5bb.firebasestorage.app',
    iosBundleId: 'com.example.petwellProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUKXEGJ-uSBCP6tw7dKmoYT0VCvS63ziU',
    appId: '1:500904711523:ios:d3303e88388ea90c98ef56',
    messagingSenderId: '500904711523',
    projectId: 'pet-well-3d5bb',
    storageBucket: 'pet-well-3d5bb.firebasestorage.app',
    iosBundleId: 'com.example.petwellProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDethRgfLvoLbyBgGzVnueOgzColBK_7UI',
    appId: '1:500904711523:web:3668905b0204604498ef56',
    messagingSenderId: '500904711523',
    projectId: 'pet-well-3d5bb',
    authDomain: 'pet-well-3d5bb.firebaseapp.com',
    storageBucket: 'pet-well-3d5bb.firebasestorage.app',
    measurementId: 'G-GXKFHJRB07',
  );
}
